### ISSUE TITLE
Make predicates unary instead of nullary

### ISSUE THREAD

**Issue by treeowl** [nikita-volkov/refined#12]
There's really no good reason to have `undefined` lurking everywhere, waiting for someone to `seq` the wrong thing. I think vanilla predicates should generally have a single constructor.

**Comment by treeowl** [comment]
Proxy passing is another option.

**Comment by chessai** [comment]
I've thought about both of these options, and I like the first one for being less clutter, and not unsafe.

**Comment by treeowl** [comment]
I guess the main questions are how it plays with the Template Haskell and
with user-defined predicates. I haven't looked into that closely.

**Comment by treeowl** [comment]
Thanks!
