### ISSUE TITLE
Expose a really unsafe refine

### ISSUE THREAD

**Issue by treeowl** [nikita-volkov/refined#13]
The advice to use `unsafeCoerce` strikes me as a bit harsh. It's also a bit dangerous, because someone could accidentally coerce the value to an unrelated type. I'd much rather see a `Refined.Unsafe` or `Refined.Internal` module exporting the actual constructor, and perhaps also a `reallyUnsafeRefine` function to get the point across.

**Comment by chessai** [comment]
I agree with this.
