### ISSUE TITLE
Refined has the wrong role signature

### ISSUE THREAD

**Issue by treeowl** [nikita-volkov/refined#14]
Currently, it says

```haskell
type role Refined phantom representational
```

This means that I can use `coerce` to prove `Q x` given any `P x` whatsoever! I think you probably should write

```haskell
type role Refined nominal nominal
```

Why should the second parameter be nominal? Consider the interaction between `GreaterThan` and `Data.Ord.Down`.

**Comment by chessai** [comment]
This makes sense. Yeah, I didn't consider interactions with `Down` at all. Thanks for pointing this out.
