### ISSUE TITLE
Drop these

### ISSUE THREAD

**Issue by treeowl** [nikita-volkov/refined#17]
The `these` package brings in a bunch of very heavy transitive dependencies (e.g., `profunctors`, `QuickCheck`, and `aeson`). Unfortunately, `refined` *does* expose the `These` type through `RefinedException`, so dropping the dependency would be a breaking change. Nevertheless, I think it would be better to write a local copy of `These` and use that instead. Users who want to convert to the official `These` type shouldn't have any serious difficulty doing so.

**Comment by chessai** [comment]
I meant to do this because I dislike using "These" for this very reason.
Will do this tomorrow
