### ISSUE TITLE
Read can be used to bypass the check

### ISSUE THREAD

**Issue by lamefun** [nikita-volkov/refined#2]
Example:

    Prelude Refined> refine 1 :: Either String (Refined ZeroToOne Int)
    Right (Refined 1)
    Prelude Refined> refine 2 :: Either String (Refined ZeroToOne Int)
    Left "The right subpredicate failed with: A subpredicate didn't fail"
    Prelude Refined> read "Refined 2" :: Refined ZeroToOne Int
    Refined 2

I hope this is an OK fix: https://github.com/nikita-volkov/refined/pull/3

**Comment by nikita-volkov** [comment]
It's merged and released now.
