### ISSUE TITLE
Version mismatch

### ISSUE THREAD

**Issue by fosskers** [nikita-volkov/refined#22]
Hi there. The current version of `refined` on Hackage is `0.3`, but the `.cabal` available in his repo is pinned to `0.2.3`. This caused me an issue while pinning dependencies in the config of one of my projects.

**Comment by chessai** [comment]
Oops! I must have pushed to hackage but not GitHub!

**Comment by chessai** [comment]
see the current HEAD: aad7c2d

**Comment by fosskers** [comment]
Thank you :)
