### ISSUE TITLE
Arbitrary instance for Refined can infinitely loop

### ISSUE THREAD

**Issue by symbiont-joseph-kachmar** [nikita-volkov/refined#40]
It looks like the `Arbitrary` instance for `Refined` types defined in `Refined.Orphan.QuickCheck` uses `suchThat`, which can loop infinitely.

https://github.com/nikita-volkov/refined/blob/master/src/Refined/Orphan/QuickCheck.hs#L50

I had initially thought `suchThat` could be replaced with `suchThatMaybe`, but this doesn't exactly work out (I don't think there's any way to `fail` in `Gen`...).

**Comment by chessai** [comment]
Okay, I agree with this. I'd take a PR.

**Comment by chessai** [comment]
Since QuickCheck catches any `ErrorCall`s thrown in `Gen`, perhaps it would be enough to loop on `suchThatMaybe` a number of times, and if it's still nothing, just call `error` with a descriptive message?

**Comment by symbiont-joseph-kachmar** [comment]
Responded in the other issue, but thanks very much for looking into this!

**Comment by chessai** [comment]
closed in #44
