### ISSUE TITLE
Add to stackage

### ISSUE THREAD

**Issue by bbarker** [nikita-volkov/refined#49]
I just confirmed the build worked as an extra-dep in my project using LTS 14.17; also, it was previously in stackage until LTS 13.11. So all told, I don't anticipate any issues.

**Comment by chessai** [comment]
@bbarker Thanks! I will do this after the 24-hour period on hackage has passed for the 0.5 release.

**Comment by chessai** [comment]
There are two relevant PRs open for this:

https://github.com/commercialhaskell/stackage/pull/5511
https://github.com/commercialhaskell/stackage/pull/5510

**Comment by chessai** [comment]
Both PRs merged, thanks
