### ISSUE TITLE
increase bounds

### ISSUE THREAD

**Issue by symbiont-sam-halliday** [nikita-volkov/refined#50]
can you please widen your constraints (ideally as a metarevision update) to

```
    , prettyprinter    >= 1.1.0.1 && < 1.7
```

allowing the use of `prettyprinter-1.6.1` (in the LTS-15). I confirmed that this works.

I have also asked some Hackage Trustees so this might happen while you are sleeping :smiley:

**Comment by chessai** [comment]
https://hackage.haskell.org/package/refined-0.4.4/revisions/

**Comment by chessai** [comment]
Done. Thanks!
