### ISSUE TITLE
Internal module

### ISSUE THREAD

**Issue by nikita-volkov** [nikita-volkov/refined#54]
@chessai What exactly do we have the `Refined.Internal` module for? Seems like all its functionality is achievable with the `Refined.Unsafe` module, without all the violation of PVP that the internal modules entail.

**Comment by chessai** [comment]
I have had this thought a lot lately, and I agree.

**Comment by nikita-volkov** [comment]
http://nikita-volkov.github.io/internal-convention-is-a-mistake/

**Comment by chessai** [comment]
resolved in db42a9c
