### ISSUE TITLE
stop using `prettyprinter`, just use `String`s

### ISSUE THREAD

**Issue by chessai** [nikita-volkov/refined#66]
This library doesn't really do anything significant with the prettyprinter library. This could be changed to `String` (or maybe `Text`) and nothing would really change. And then users could use whatever pretty printer library they want on top of that.

Polling for opinions @symbiont-sam-halliday (feel free to ask your coworkers) @nikita-volkov

**Comment by nikita-volkov** [comment]
I agree! The lesser dependencies the better, especially so when we don't really need one.

**Comment by symbiont-sam-halliday** [comment]
My opinion on `Pretty` is that it is basically "`Show`, only worse" ... so I fully endorse its removal :grimacing:

**Comment by chessai** [comment]
Cool. We already depend on text so it's no problem.

**Comment by chessai** [comment]
Closed by 0e242247d83db128f0436344ddf19973982c70d4
