### ISSUE TITLE
new error display

### ISSUE THREAD

**Issue by chessai** [nikita-volkov/refined#69]
Not really anything to resolve here. Just wanted to show off the new error display if you haven't already seen it, @nikita-volkov @symbiont-sam-halliday.

See https://hackage.haskell.org/package/refined-0.5.1/docs/Refined.html#v:displayRefineException

**Comment by chessai** [comment]
closing since there's no actual issue

**Comment by nikita-volkov** [comment]
Oh. This is cool. So we keep the prettyprinter after all, right?

**Comment by chessai** [comment]
No, this is done without the prettyprinter
