### ISSUE TITLE
GHC-9 compatible release?

### ISSUE THREAD

**Issue by locallycompact** [nikita-volkov/refined#75]
Hi could there be a release with the new GHC-9 fix?

If new versions of this library are not a priority for anyone I can offer to maintain releases.

**Comment by chessai** [comment]
Sorry, I'm going to do the release, after I get back from vacation. I don't have access to a computer right now, just my phone.

**Comment by locallycompact** [comment]
Ok thank you.

**Comment by JackKelly-Bellroy** [comment]
It would be handy to get the new instances onto Hackage, too - I can add a GHC9 entry to the changelog if that would help? (If there's anything else that would help, let me know)

**Comment by JackKelly-Bellroy** [comment]
@chessai is there anything I can do to help out here?

**Comment by chessai** [comment]
Published [refined-0.6.3](https://hackage.haskell.org/package/refined-0.6.3)
