### ISSUE TITLE
Comaintainer

### ISSUE THREAD

**Issue by chessai** [nikita-volkov/refined#8]
@nikita-volkov I would like to offer to be a comaintainer for this library.

**Comment by nikita-volkov** [comment]
Nice work! I've sent you an invite

**Comment by chessai** [comment]
Thank you.

**Comment by nikita-volkov** [comment]
I've added you to the package's maintainers on Hackage

**Comment by chessai** [comment]
Thank you, I was going to ask about this when I got home from work.
