### ISSUE TITLE
Expose "Value" in the error message of predicates?

### ISSUE THREAD

**Issue by peterstorm** [nikita-volkov/refined#92]
Hello!

First of all, thank you for a great library!

I just wanted to ask if there was a specific reason that you do not "expose" the value that failed the predicate, in the error messages?

Like in the `FromTo` predicate that we use alot, it would be nice to see what the caller sent to us, and the actual value is there.

Edit: Happy to make a PR, if there  is no obvious reason, you shouldn't show the incoming value.

**Comment by raehik** [comment]
Assuming you're refining using `refine :: forall p x. (Predicate p x) => x -> Either RefineException (Refined p x)`, you already have the pre-refine value. You could replace calls to `refine` with something that shows the exception along with the refined value (using `Show x`) if you wanted.

To do this in the predicate you'd have to add `Show x` and maybe `Typeable x` constraints to the predicate instance. It's useful when you're doing "fine-grained" refining and combining various possible failures into a single error (I did something similar in [Strongweak.Strengthen](https://github.com/raehik/strongweak/blob/7fb29d3e8b1f9986990a4516741e2ddcc6b6356f/src/Strongweak/Strengthen.hs#L119)), but isn't needed & restricts unnecessarily in the base case. Maybe you're looking for something like that? In which case, try wrapping `RefineException` into a larger data type.

**Comment by peterstorm** [comment]
Oh sorry, we're using the instances for `FromJSON` your library supplies, so we don't get to do that, as far as I can see? We would have to overlap the instances of `FromTo` as far as I can see, or define manual instances for our newtypes, which is tedious. 

That's why I was wondering why the  default instance of `FromTo` throws away the value in the `validate` implementation.

**Comment by chessai** [comment]
> Oh sorry, we're using the instances for `FromJSON` your library supplies, so we don't get to do that, as far as I can see? We would have to overlap the instances of `FromTo` as far as I can see, or define manual instances for our newtypes, which is tedious.
> 
> That's why I was wondering why the default instance of `FromTo` throws away the value in the `validate` implementation.

Can you answer (with types) what you're looking for?
Aeson doesn't exactly give you rich errors - `FromJSON`'s `parseJSON` method returns a `Parser a`, and the primary failure mode there is `MonadFail`'s `fail` - just a String.
This is a failure of `aeson` IMO - since it should allow for a polymorphic error type, or one that it can inject context into. c.f. [bytesmith](https://hackage.haskell.org/package/bytesmith-0.3.9.0/docs/Data-Bytes-Parser.html).

I suppose you could do something like
```haskell
newtype RefinedJsonResult p a
  = RefinedValue a
  | RefinedJsonDecodeError
      { json :: Aeson.Value
      , aesonErrorMessage :: String
      }
  | RefinedError
      { json :: Aeson.Value
      , refineException :: RefineException
      }
  deriving newtype (Eq)
type role RefinedJSON nominal nominal

instance (ToJSON a) => ToJSON (RefinedJsonResult p a) where
  toJSON = \case
    RefinedValue a -> toJSON a
    RefinedValue v _ -> v

instance forall p a. (FromJSON a, Predicate p a) => FromJSON (RefinedJsonResult p a) where
  parseJSON json = case Aeson.parseEither (Aeson.parseJSON @a) json of
    Left aesonErrorMessage -> pure $ RefinedJsonDecodeError {..}
    Right x -> case refine_ @p @a x of
      Left refineException -> pure $ RefinedError {..}
      Right a -> pure $ RefinedValue a
```

Note that this can actually be abstracted over multiple encodings, not just ToJSON/FromJSON, but I kept it simpler here.

**Comment by peterstorm** [comment]
Sorry, I haven't been able to explain myself well enough - all the above is what we want to avoid , but we have done it for some custom arbitrary instances 😅

I don't understand why the actual instance is throwing away the value and just writing `Value` when it could be writing out the value that is given to it.

We do that in our custom refined types, so I guess that's the whole question - if there's a good reason for not doing it, at actual instance where you define `validate`.

https://hackage.haskell.org/package/refined-0.8/docs/src/Refined.html#FromTo

**Comment by chessai** [comment]
> Sorry, I haven't been able to explain myself well enough - all the above is what we want to avoid , but we have done it for some custom arbitrary instances 😅
> 
> I don't understand why the actual instance is throwing away the value and just writing `Value` when it could be writing out the value that is given to it.
> 
> We do that in our custom refined types, so I guess that's the whole question - if there's a good reason for not doing it, in the actual instance where you implement `validate`.
> 
> https://hackage.haskell.org/package/refined-0.8/docs/src/Refined.html#FromTo
> 
> When you then do `GeneralizedNewtypeDeriving` everything just works, tm, and you get more informative error messages, without having to do any work 😅 But I guess we can just overwrite the instance for Predicate on FromTo, again, it was mostly just a question 😄

I don't understand. Are you asking why `validate` does not return x?

Can you explain with types what you're looking for?

**Comment by peterstorm** [comment]
Yeah, I don't understand why it's like this:

```Haskell
instance ( Ord x, Num x, KnownNat mn, KnownNat mx, mn <= mx
         ) => Predicate (FromTo mn mx) x where
  validate p x = do
    let mn' :: Integer
mn' = nv @mn
    let mx' = nv @mx
    if x >= fromIntegral mn' && x <= fromIntegral mx'
    then Nothing
    else
      let msg = [ "Value is out of range (minimum: "
                , i2text mn'
                , ", maximum: "
                , i2text mx'
                , ")"
                ] |> mconcat
      in throwRefineOtherException (typeRep p) msg
```

And not:
```Haskell

instance ( Ord x, Num x, Show x, KnownNat mn, KnownNat mx, mn <= mx
         ) => Predicate (FromTo mn mx) x where
  validate p x = do
    let mn' :: Integer
mn' = nv @mn
    let mx' = nv @mx
    if x >= fromIntegral mn' && x <= fromIntegral mx'
    then Nothing
    else
      let msg = [ show x
                ," is out of range (minimum: "
                , i2text mn'
                , ", maximum: "
                , i2text mx'
                , ")"
                ] |> mconcat
      in throwRefineOtherException (typeRep p) msg

```

For example, including the value that is out of range in the error message? Again, we can just overwrite the instance if it isn't intended to be done like this 😄

**Comment by chessai** [comment]
> WeYeah, I don't understand why it's like this:
> 
> ```haskell
> instance ( Ord x, Num x, KnownNat mn, KnownNat mx, mn <= mx
>          ) => Predicate (FromTo mn mx) x where
>   validate p x = do
>     let mn' :: Integer
>         mn' = nv @mn
>     let mx' = nv @mx
>     if x >= fromIntegral mn' && x <= fromIntegral mx'
>     then Nothing
>     else
>       let msg = [ "Value is out of range (minimum: "
>                 , i2text mn'
>                 , ", maximum: "
>                 , i2text mx'
>                 , ")"
>                 ] |> mconcat
>       in throwRefineOtherException (typeRep p) msg
> ```
> 
> And not:
> 
> ```haskell
> instance ( Ord x, Num x, Show x, KnownNat mn, KnownNat mx, mn <= mx
>          ) => Predicate (FromTo mn mx) x where
>   validate p x = do
>     let mn' :: Integer
> mn' = nv @mn
>     let mx' = nv @mx
>     if x >= fromIntegral mn' && x <= fromIntegral mx'
>     then Nothing
>     else
>       let msg = [ show x
>                 , " is out of range (minimum: "
>                 , i2text mn'
>                 , ", maximum: "
>                 , i2text mx'
>                 , ")"
>                 ] |> mconcat
>       in throwRefineOtherException (typeRep p) msg
> ```
> 
> For example, including the value that is out of range in the error message? Again, we can just overwrite the instance if it isn't intended to be done like this 😄

So, for logging purposes, I'm guessing.

The reason this is not done is for at least a couple reasons

- `x` could be arbitrarily large, blowing up the exception
- we would have to require yet another constraint on `x`, probably `Show`, which i found unacceptable

I suppose that you could make the exception for numeric refinements. But that is not something I've considered before and it would require some thinking about the design.

For now, I would advise making your own refinement, copying and modifying the code for FromTo.

**Comment by peterstorm** [comment]
Thank you! Apologies for not making it clearer sooner 😅
