### ISSUE TITLE
Release 0.8.1.0

### ISSUE THREAD

**Issue by JackKelly-Bellroy** [nikita-volkov/refined#95]
Would it be possible to cut 0.8.1.0 and send it to Hackage? It's been a few months since #90 and #91 landed, and if there's nothing else that needs batching up, it would allow me to remove the `source-repository-package` stanzas from my `cabal.project` files.

**Comment by JackKelly-Bellroy** [comment]
Alternatively, if there's something you really want in for the next release, maybe we can PR it?

**Comment by chessai** [comment]
Completely missed this, was really busy last month. Yes, there should be a new release soon.

**Comment by chessai** [comment]
0.8.1 published: [Hackage](https://hackage.haskell.org/package/refined-0.8.1), [Git tag](https://github.com/nikita-volkov/refined/releases/tag/v0.8.1)

**Comment by JackKelly-Bellroy** [comment]
Thank you very much for this.
