### ISSUE TITLE
GHC 9.6.1

### ISSUE THREAD

**Issue by tbidne** [nikita-volkov/refined#96]
As with [`these-skinny`](https://github.com/chessai/these-skinny/issues/4), this appears to work with revisions, but I understand if this merits a closer look. No rush.

```
allow-newer: refined-0.8:base
allow-newer: refined-0.8:mtl
allow-newer: refined-0.8:template-haskell
```

Thanks!

**Comment by chessai** [comment]
I confirmed that `cabal build --allow-newer=these-skinny:base --constraint="template-haskell == 2.20.0.0" --constraint="mtl == 2.3.1"` succeeds with GHC 9.6.1

**Comment by chessai** [comment]
0.8.1 published: [Hackage](https://hackage.haskell.org/package/refined-0.8.1), [Git tag](https://github.com/nikita-volkov/refined/releases/tag/v0.8.1)

**Comment by tbidne** [comment]
Marvelous, thanks again!
